name: deploy basic network

on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        required: false
        description: Azure resource group name (Leave empty to default to '{github_name}-{location}')
        type: string
      location:
        required: true
        description: Azure resource group location
        type: choice
        options:
        - westus2
        - centralus
      deployment-mode:
        required: true
        description: Azure deployment mode
        type: choice
        options:
        - Complete
        - Incremental
        - Validate

  push:
    branches:

env:
  IS_MAIN_PUSH: ${{ github.ref == 'refs/heads/main' }}
  AZURE_RESOURCE_GROUP_LOCATION: ${{ github.event.inputs.location || 'westus2' }}
  AZURE_DEPLOYMENT_NAME: ${{ format('basic-network.{0}.{1}', github.actor, github.RUN_ID) }}
  AZURE_DEPLOYMENT_MODE: >-
    ${{ 
      github.event.inputs.deployment-mode || 'Complete'
    }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set current Azure Subscription and update environment variables
      run: |
        az account show
        echo "AZURE_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)" >> $GITHUB_ENV
        echo "AZURE_RESOURCE_GROUP_NAME=${{ github.event.inputs.resource-group-name || format('{0}-{1}', github.actor, env.AZURE_RESOURCE_GROUP_LOCATION) }}" >> $GITHUB_ENV

    - name: Create Azure Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name $AZURE_RESOURCE_GROUP_NAME --location $AZURE_RESOURCE_GROUP_LOCATION
          echo 🎉

    - name: Deploy Bicep templates 💪
      id: azure-deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        deploymentMode: ${{ env.AZURE_DEPLOYMENT_MODE }}
        deploymentName: ${{ env.AZURE_DEPLOYMENT_NAME }}
        template: ./bicep/main.santiago.bicep
        failOnStdErr: false

    - name: Save deployment output
      env:
        AZURE_DEPLOY_OUTPUT: ${{ toJSON(steps.azure-deploy.outputs) }}
      run: |
        mkdir artifacts
        echo $AZURE_DEPLOY_OUTPUT
        echo $AZURE_DEPLOY_OUTPUT >> artifacts/deployment.json

    - name: Upload Azure Deploy Output
      uses: actions/upload-artifact@v2
      with:
        name: Deployment
        path: artifacts

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git