name: deploy basic network (terraform)

on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        required: false
        description: Azure resource group name (Leave empty to default to 'kraken-tf-{location}')
        type: string
      location:
        required: true
        description: Azure resource group location
        type: choice
        options:
        - westus2
        - centralus
      deployment-mode:
        required: true
        description: Azure deployment mode
        type: choice
        options:
        - Complete
        - Incremental
        - Validate
      private-storage-endpoint:
        required: true
        description: Azure Storage only accessible from vnet
        type: boolean
        default: false

  push:
    branches:
    paths:
      - .github/workflows/basic-network-terraform.yml
      - terraform/**

defaults:
  run:
    working-directory: ./terraform

env:
  IS_MAIN_PUSH: ${{ github.ref == 'refs/heads/main' }}
  MAIN_BICEP_TEMPLATE_PATH: ./bicep/main-basic-network.bicep
  AZURE_RESOURCE_GROUP_LOCATION: ${{ github.event.inputs.location || 'westus2' }}
  AZURE_DEPLOYMENT_NAME: ${{ format('basic-network-terraform.{0}.{1}', github.actor, github.RUN_ID) }}
  AZURE_DEPLOYMENT_MODE: >-
    ${{ 
      github.event.inputs.deployment-mode || 
      (github.ref == 'refs/heads/main' && 'Complete' || 'Validate')
    }}
  AZURE_DEPLOYMENT_USE_PRIVATE_STORAGE_ENDPOINT: ${{ github.event.inputs.private-storage-endpoint || 'false' }}
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1

    - name: terraform fmt
      id: fmt
      run: terraform fmt -check -diff
      continue-on-error: true

    - name: terraform init
      id: init
      run: terraform init

    - name: terraform validate
      id: validate
      run: terraform validate -no-color

    - name: terraform plan
      id: plan
      run: |
        terraform plan -input=false -no-color \
          -var "resource_group_name=${{ env.AZURE_RESOURCE_GROUP_NAME }}" \
          -var "resource_group_location=${{ env.AZURE_RESOURCE_GROUP_LOCATION }}" \
          -out=azure.tfplan

    - name: terraform apply
      id: azure-deploy
      run: terraform apply "azure.tfplan"

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git